"""User and UserSession models: DB-backed authentication (auth plan Task 1).

The session table is named UserSession at the ORM layer, not Session -- a
model class literally called Session would shadow sqlalchemy.orm.Session,
which is imported by type hint (`db: Session`) throughout deps.py, every
router, the seed scripts, and the tests. UserSession sidesteps that clash
for a one-line class-name cost; the underlying table is still "sessions"
(see the auth plan, Task 1).

Session tokens are never stored in plaintext: only the SHA-256 hex digest
of the opaque token (secrets.token_urlsafe(32), generated by the /auth
router) is persisted in token_hash, so a database leak does not leak
usable bearer tokens. The raw token is returned to the client exactly
once, at login.

No DB-level ON DELETE CASCADE exists anywhere in this schema (see
architecture.md's note on migration 004); User -> UserSession cascade is
ORM-level (relationship(cascade="all, delete-orphan")), the same pattern
GeneratedRota already uses for RotaSession/RotaClosure/generation_log.

password_hash stores a bcrypt hash. bcrypt silently truncates input at 72
bytes, so the max-length-72 rule is enforced at the Pydantic schema layer
-- nothing about that truncation is visible from the model itself.

access_level is the permission tier. It defaults to NURSE -- the lowest
tier -- both here and as the server_default in migration 028: an
accidental viewer is recoverable, an accidental manager is a silent
security hole. The API never relies on that default (UserIn requires
access_level), so it only ever applies to rows inserted directly, e.g. by
a script or a test.
"""
import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ..database import Base
from .enums import AccessLevel, enum_col


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    name: Mapped[str] = mapped_column(String, nullable=False)
    password_hash: Mapped[str] = mapped_column(String, nullable=False)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    access_level: Mapped[AccessLevel] = mapped_column(
        enum_col(AccessLevel), nullable=False, default=AccessLevel.NURSE
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )

    sessions: Mapped[list["UserSession"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<User {self.email}>"


class UserSession(Base):
    __tablename__ = "sessions"

    id: Mapped[int] = mapped_column(primary_key=True)
    token_hash: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id"), nullable=False, index=True
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )
    expires_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    user: Mapped["User"] = relationship(back_populates="sessions")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<UserSession user_id={self.user_id}>"
