"""User and UserSession models: DB-backed authentication (auth plan Task 1).

The session table is named UserSession at the ORM layer, not Session -- a
model class literally called Session would shadow sqlalchemy.orm.Session,
which is imported by type hint (`db: Session`) throughout deps.py, every
router, the seed scripts, and the tests. UserSession sidesteps that clash
for a one-line class-name cost; the underlying table is still "sessions"
(see the auth plan, Task 1).

Session tokens are never stored in plaintext: only the SHA-256 hex digest
of the opaque token (secrets.token_urlsafe(32), generated by the /auth
router) is persisted in token_hash, so a database leak does not leak
usable bearer tokens. The raw token is returned to the client exactly
once, at login.

School holidays aside, no DB-level ON DELETE CASCADE exists anywhere in
this schema (see 001_initial_schema.py's docstring); User -> UserSession cascade is
ORM-level (relationship(cascade="all, delete-orphan")), the same pattern
GeneratedRota already uses for RotaSession/RotaClosure/generation_log.

password_hash stores a bcrypt hash. bcrypt silently truncates input at 72
bytes, so the max-length-72 rule is enforced at the Pydantic schema layer
-- nothing about that truncation is visible from the model itself.

`permissions` is the per-user permission set (fine-grained permissions
plan, D2/D3), which replaces `access_level` as the thing authorization
reads; `access_level` survives beside it as a decorative label -- see
below. As of this commit the column is written, validated and returned but
not yet consulted: the gates in api/deps.py still read `access_level`
until the gate rework lands. The set is a small JSON object, always read
whole and never joined against, so it is one column rather than five or an
association table; adding a sixth permission is then a code change, not a
migration.

The column type is portable `sqlalchemy.JSON`, not `JSONB`: the test suite
builds SQLite straight from these models via `create_all`. It is wrapped
in `MutableDict.as_mutable` because a plain JSON column is not
change-tracked -- `user.permissions["clinical"] = "write"` would be
silently dropped at commit, and the failure would look like a gating bug
rather than a persistence one. The server_default denies everything, for
the same reason access_level's does.

access_level is the legacy permission tier, on its way to being a label
only. Once the gates move across, nothing will authorize off it -- but it
stays, because the audit log snapshots it, "Manager" is
still a useful word in the UI, and AccessLevel is a native Postgres enum
type, so removing a value would cost an ALTER TYPE migration for no
functional gain. It defaults to NURSE -- the lowest
tier -- as both the Python-side default and the server_default: an
accidental viewer is recoverable, an accidental manager is a silent
security hole. The API never relies on that default (UserIn requires
access_level), so the server_default only ever applies to rows inserted
by direct SQL, e.g. by a script or a manual psql session.

doctor_id / reception_staff_id optionally link a login to the person it
belongs to on each rota. Both are nullable: a practice manager has a login
and no rota presence, and a locum may have a Doctor row and no login, so
"unlinked" is a normal, permanent state on both sides rather than a gap to
be filled in.

The columns live here, on users, and not on doctors/reception_staff,
because the link is a privilege grant -- it decides whose rota is "yours"
and, in any later feature, what you may act on. Users are manager-only to
edit, while the Doctors page is writable by any admin; a doctor_user_id
column on doctors would therefore let an admin hand themselves a clinical
identity.

They are two typed foreign keys rather than one polymorphic
(staff_kind, staff_id) pair. The polymorphic form saves a column and gives
up referential integrity to do it, in a schema that has exactly two staff
types and no prospect of a third.

Each column carries its own unique index, and that -- not any constraint on
the staff tables -- is what makes the relationship 0..1 on both sides: at
most one user per staff row, at most one staff row per user. It works
because SQLite and Postgres both treat NULLs as distinct in a unique index,
so any number of users may sit unlinked while no two users can claim the
same doctor. Setting both columns on one user is allowed: a nurse who also
covers reception is real, and permitting it costs nothing.

The link is orthogonal to access_level; neither derives the other. A
partner who runs the rota needs the manager tier and a doctor link, a
practice manager needs neither. AccessLevel.DOCTOR stays what its docstring
says it is -- a label, permission-identical to NURSE.
"""
import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    String,
    UniqueConstraint,
    text,
)
from sqlalchemy.ext.mutable import MutableDict
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ..database import Base
from .enums import AccessLevel, enum_col
from .permissions import (
    DEFAULT_PERMISSIONS_JSON,
    PermissionSetDict,
    default_permissions,
)

if TYPE_CHECKING:
    from .doctor import Doctor
    from .reception import ReceptionStaff


class User(Base):
    __tablename__ = "users"
    __table_args__ = (
        UniqueConstraint("email", name="uq_users_email"),
        # Named explicitly: the migration's downgrade drops them by name.
        Index("uq_users_doctor_id", "doctor_id", unique=True),
        Index("uq_users_reception_staff_id", "reception_staff_id", unique=True),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str] = mapped_column(String, nullable=False)
    name: Mapped[str] = mapped_column(String, nullable=False)
    password_hash: Mapped[str] = mapped_column(String, nullable=False)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    access_level: Mapped[AccessLevel] = mapped_column(
        enum_col(AccessLevel),
        nullable=False,
        default=AccessLevel.NURSE,
        server_default=AccessLevel.NURSE.value,
    )
    # What this login may actually do. See the module docstring for the
    # column type, and models/permissions.py for the shape.
    permissions: Mapped[PermissionSetDict] = mapped_column(
        MutableDict.as_mutable(JSON),
        nullable=False,
        default=default_permissions,
        server_default=text(f"'{DEFAULT_PERMISSIONS_JSON}'"),
    )
    # The rota person this login belongs to, if any. See the module
    # docstring for why these sit here and why each is uniquely indexed.
    doctor_id: Mapped[int | None] = mapped_column(
        ForeignKey("doctors.id"), nullable=True
    )
    reception_staff_id: Mapped[int | None] = mapped_column(
        ForeignKey("reception_staff.id"), nullable=True
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )

    # No back_populates on either: nothing on the staff side needs to
    # navigate to a user, and a back-reference would put a user-shaped
    # attribute on Doctor -- exactly what keeping the columns here avoids.
    doctor: Mapped["Doctor | None"] = relationship()
    reception_staff: Mapped["ReceptionStaff | None"] = relationship()

    sessions: Mapped[list["UserSession"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<User {self.email}>"


class UserSession(Base):
    __tablename__ = "sessions"
    __table_args__ = (UniqueConstraint("token_hash", name="uq_sessions_token_hash"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    token_hash: Mapped[str] = mapped_column(String, nullable=False)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id"), nullable=False, index=True
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )
    expires_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    user: Mapped["User"] = relationship(back_populates="sessions")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<UserSession user_id={self.user_id}>"
